params:
  ArticulationObject:
    kitchen:
      name: kitchen02
      path: "./data/kitchen02/kitchen02.usda"
      scale: [3, 3, 3]
      pos: [0.4, 0.3, 0.6] # setting for 3,3,3
      # scale: [3, 3, 3]
      # pos: [0.5, 0.7, 0.6]
      rot:
        axis: [0, 1, 2]
        # angles: [-0.14, -0.07, -2.1]\
        angles: [-0.14, -0.07, -2.1]
      disable_gravity: True
      enabled_self_collisions: False
      joints:
        drawer_revolute_joint_2: 0.0
        drawer_revolute_joint_3: 0.0
        drawer_revolute_joint_4: 0.0
        drawer_revolute_joint_5: 0.0
        drawer_revolute_joint_6: 0.0
        drawer_revolute_joint_7: -0.0
        drawer_revolute_joint_8: 0.0
        drawer_revolute_joint_9: -0.0
        drawer_revolute_joint_10: -0.0
        drawer_revolute_joint_11: -0.0
        drawer_revolute_joint_12: 0.0
        drawer_revolute_joint_13: -0.0

        #revolute_joint
        drawer_prismatic_joint_0: 0.0
        drawer_prismatic_joint_1: 0.0

  RigidObject:
    mustard_bottle:
      path: "/home/raymond/projects/clean-up-the-kitchen/data/ycb/Axis_Aligned/006_mustard_bottle.usd"
      scale: [1, 1, 1]
      pos: [1.3, 2.7, 0.9]
      rot:
        axis: [0]
        angles: [-1.57]
    master_chef_can:
      path: "/home/raymond/projects/clean-up-the-kitchen/data/ycb/Axis_Aligned/002_master_chef_can.usd"
      scale: [1, 1, 1]
      scale: [1, 1, 1]
      pos: [1.3, 2.8, 0.9]
      rot:
        axis: [0]
        angles: [-1.57]
    sugar_box:
      path: "/home/raymond/projects/clean-up-the-kitchen/data/ycb/Axis_Aligned/004_sugar_box.usd"
      scale: [1, 1, 1]
      pos: [1.3, 2.9, 0.9]
      rot:
        axis: [0]
        angles: [-1.57]
    tomato_soup_can:
      path: "/home/raymond/projects/clean-up-the-kitchen/data/ycb/Axis_Aligned/005_tomato_soup_can.usd"
      scale: [1, 1, 1]
      pos: [1.3, 3.0, 0.9]
      rot:
        axis: [0]
        angles: [-1.57]
    bowl:
      path: "/home/raymond/projects/clean-up-the-kitchen/data/ycb/Axis_Aligned/024_bowl.usd"
      scale: [1, 1, 1]
      pos: [1.3, 3.1, 0.9]
      rot:
        axis: [0]
        angles: [-1.57]
