params:
  ArticulationObject:
    kitchen:
      name: kitchen01
      path: "./data/cs_kitchen_n/uiuc_kitchen.usda"
      scale: [2., 2., 2.]
      pos: [-0.4, -0.1, 0.6]
      rot:
        axis: [0, 1, 2]
        # angles: [-0.211446638879, -0.0232128790515, -0.105086274263]
        # angles: [0.20980, 0.039339, -1.33866753628]
        angles: [-0.211446638879, -0.0232128790515, -1.6235227235]
      disable_gravity: True
      enabled_self_collisions: False
      joints:
        drawer_revolute_joint_0: 0.0
        drawer_revolute_joint_1: 0.0
        drawer_revolute_joint_2: 0.0
        drawer_revolute_joint_3: 0.0
        drawer_revolute_joint_4: 0.0
        drawer_revolute_joint_5: 0.0
        drawer_revolute_joint_6: 0.0
        drawer_revolute_joint_11: -0.0
        drawer_revolute_joint_12: 0.0
        drawer_revolute_joint_13: -0.0
        drawer_revolute_joint_14: 0.0
        drawer_revolute_joint_15: 0.0

        #revolute_joint
        drawer_prismatic_joint_7: 0.0
        drawer_prismatic_joint_8: 0.0
        drawer_prismatic_joint_9: 0.0
        drawer_prismatic_joint_10: 0.0

  RigidObject:
    # cleanex:
    #   path: "/home/raymond/projects/clean-up-the-kitchen/data/segmented_objects/kleanex_test2.usd"
    #   scale: [100000, 100000, 100000]
    #   pos: [0.6, 0.27962, 0.4]
    #   rot:
    #     axis: [0]
    #     angles: [-1.57]
    # master_chef_can:
    #   path: "/home/raymond/projects/clean-up-the-kitchen/data/segmented_objects/idkobject2.usd"
    #   scale: [1, 1, 1]
    #   pos: [0.79216, 0.43599, 0.4]
    #   rot:
    #     axis: [0]
    #     angles: [-1.57]
    kettle:
        path: "/home/raymond/projects/clean-up-the-kitchen/data/segmented_objects/kettle_test1.usd"
        scale: [1.5, 1.5, 1.5]
        pos: [0.40, -1.0, 0.45738]
        rot:
          axis: [0]
          angles: [-0]
        # pose_range:
        #   x: [0.0, 0.10]
        #   y: [-0.25, 0.05]
        #   z: [0.0, 0.0]
        #   yaw: [-1.0, 1.0]
    # sponge:
    #   path: "/home/raymond/projects/clean-up-the-kitchen/data/segmented_objects/sponge_test1.usd"
    #   scale: [2, 2, 2]
    #   pos: [0.35, -0.80, 0.40738]
    #   rot:
    #     axis: [0]
    #     angles: [0]

    # mustard_bottle:
    #   path: "/home/raymond/projects/clean-up-the-kitchen/data/ycb/Axis_Aligned/006_mustard_bottle.usd"
    #   scale: [1, 1, 1]
    #   pos: [0.40, -0.3, 0.30738]
    #   rot:
    #     axis: [0]
    #     angles: [-1.57]