usd_info_path: "./data/weirdlab_xform_mapping.yml"
log_dir: "./logs"

sb3:
  seed: 42
  n_timesteps: 1e10
  policy: 'MlpPolicy'
  batch_size: 128
  n_steps: 512
  gamma: 0.99
  gae_lambda: 0.9
  n_epochs: 20
  ent_coef: 0.0
  sde_sample_freq: 4
  max_grad_norm: 0.5
  vf_coef: 0.5
  learning_rate: 3e-5
  use_sde: true
  clip_range: 0.4
  device: "cuda:0"
  policy_kwargs: |
    dict(
        log_std_init=-1,
        ortho_init=False,
        activation_fn=nn.ReLU,
        net_arch=dict(pi=[256, 256], vf=[256, 256])
    )

video:
  enabled: false
  viewer_resolution: [320, 240]
  viewer_eye: [-4.2, -2.5, 2.0]
  viewer_lookat: [3.8, 2.7, -1.2]
  video_folder: "videos"
  save_steps: 2500
  video_length: 250



###############################################################################
# GRASP CONFIG START
###############################################################################

grasp:
  data:
    root_dir: ''
    num_points: 25000
    num_object_points: 1024
    world_coord: true
    num_rotations: 8
    grid_resolution: 0.01
    jitter_scale: 0.0
    contact_radius: 0.005
    robot_prob: 1.0
    offset_bins: [0, 0.00794435329, 0.0158887021, 0.0238330509, 0.0317773996, 0.0397217484, 0.0476660972, 0.055610446, 0.0635547948, 0.0714991435, 0.08]
    synthetic_pcd: false

  m2t2:
    scene_encoder:
      type: 'pointnet2_msg'
      num_points: 16384
      downsample: 4
      radius: 0.05
      radius_mult: 2
      use_rgb: false

    object_encoder:
      type: 'pointnet2_msg_cls'
      num_points: 1024
      downsample: 4
      radius: 0.05
      radius_mult: 2
      use_rgb: false

    contact_decoder:
      mask_feature: 'res0'
      in_features: ['res1', 'res2', 'res3']
      place_feature: 'res4'
      object_in_features: ['res1', 'res2', 'res3']
      embed_dim: 256
      feedforward_dim: 512
      num_scales: 3
      num_layers: 9
      num_heads: 8
      num_grasp_queries: 100
      num_place_queries: 8
      language_context_length: 0
      language_token_dim: 256
      use_attn_mask: true
      use_task_embed: true
      activation: 'GELU'

    action_decoder:
      use_embed: false
      max_num_pred: null
      hidden_dim: 256
      num_layers: 2
      num_params: 0
      activation: 'GELU'
      offset_bins: [0, 0.00794435329, 0.0158887021, 0.0238330509, 0.0317773996, 0.0397217484, 0.0476660972, 0.055610446, 0.0635547948, 0.0714991435, 0.08]

    matcher:
      object_weight: 2.0
      bce_weight: 5.0
      dice_weight: 5.0

    grasp_loss:
      object_weight: 2.0
      not_object_weight: 0.1
      pseudo_ce_weight: 0.0
      bce_topk: 512
      bce_weight: 5.0
      dice_weight: 5.0
      deep_supervision: true
      recompute_indices: true
      adds_pred2gt: 100.0
      adds_gt2pred: 0.0
      adds_per_obj: false
      contact_dir: 0.0
      approach_dir: 0.0
      offset: 1.0
      param: 1.0
      offset_bin_weights: [0.16652107, 0.21488856, 0.37031708, 0.55618503, 0.75124664, 0.93943357, 1.07824539, 1.19423112, 1.55731375, 3.17161779]

    place_loss:
      bce_topk: 1024
      bce_weight: 5.0
      dice_weight: 5.0
      deep_supervision: true

  optimizer:
    type: 'ADAMW'
    base_batch_size: 16
    base_lr: 0.0001
    backbone_multiplier: 1.0
    grad_clip: 0.01
    weight_decay: 0.05

  train:
    mask_thresh: 0.5
    num_gpus: 8
    port: '1234'
    batch_size: 16
    num_workers: 8
    num_epochs: 160
    print_freq: 25
    plot_freq: 50
    save_freq: 10
    checkpoint: null
    log_dir: ''

  eval:
    data_dir: ''
    checkpoint: '/home/arhan/Downloads/m2t2.pth'
    mask_thresh: 0.4
    object_thresh: 0.4
    num_runs: 1
    world_coord: true
    surface_range: 0.02
    placement_height: 0.02
    placement_vis_radius: 0.3


###############################################################################
# GRASP CONFIG END
###############################################################################
